############################################################################
#
#  Primary targets:
#    all           - the default target; synonym for 'rocq'
#    rocq          - builds all .vo files
#    doc           - synonym for 'documentation'
#    install       - copy to rocq library location
#    clean         - removes generated files
#
############################################################################

ROCQC = rocq compile
ROCQDEP = rocq dep
ROCQDOC = rocq doc

MODULES := ind_equiv
TEX := $(MODULES:%=latex/%.v.tex)

## Library name used for the imports in Rocq

LIBNAME=IndEquiv

## Name of the submakefile generated by rocq makefile

ROCQMKFILENAME=ind_equiv_make.mk

############################################################################

.PHONY: all clean rocq doc force
.SUFFIXES: .v .vo .v.d .v.glob

all: rocq

rocq: $(ROCQMKFILENAME) 
	@$(MAKE) -f $(ROCQMKFILENAME) -C src

%.mk : Makefile _%
	rocq makefile -f _$* -o $*.mk

$(ROCQMKFILENAME): Makefile
	cd src && { echo "-R . $(LIBNAME) " ; ls *.v ; } > _RocqProject && rocq makefile -f _RocqProject -o $(ROCQMKFILENAME)

install: all
	@$(MAKE) -f $(ROCQMKFILENAME) install

clean:
	@if [ -f src/$(ROCQMKFILENAME) ]; then $(MAKE) -C src -f $(ROCQMKFILENAME) clean; fi
	rm -f src/$(ROCQMKFILENAME) src/_RocqProject src/*.mk.conf
	rm -f latex/*.aux latex/*.log latex/*.out latex/*.bbl latex/*.blg latex/*.toc latex/*.v.tex latex/*.pag

force:

$(TEX): force
	$(ROCQDOC) --gallina --interpolate --latex --body-only -s \
			$(patsubst %.v.tex,src/%.v,$(notdir $@)) -o $@

doc: latex/relatorio.pdf $(TEX)

latex/relatorio.pdf: latex/relatorio.tex $(TEX) 
	cd latex ; pdflatex relatorio ; pdflatex relatorio ; pdflatex relatorio

pdf:
	evince latex/relatorio.pdf&